In [ ]:
import numpy as np
import sympy as sp



Pregunta 2

a)

In [ ]:
I = np.eye(6)
A1 = np.array([[0.7,0.1,0],[0,0.4,0.1],[0.9,0,0.8]]);
A2 = np.array([[-0.2,0,0],[0,0.1,0.1],[0,0,0]])
A = np.block([[A1,A2],[np.eye(3),np.zeros((3,3))]])
v = np.array([[2],[1],[0]])
V = np.block([[v],[np.zeros((3,1))]])
B = np.array([[10,2,0,2,0.2,0.2],[0,2,0,0,0.2,0.2],
[45,9,5,9,0.9,0.9],
[10,2,0,3,0.2,0.2],
[0,2,0,0,1.2,0.2],
[45,9,5,9,0.9,1.9]])


In [ ]:
(I-A)

array([[ 0.3, -0.1,  0. ,  0.2,  0. ,  0. ],
       [ 0. ,  0.6, -0.1,  0. , -0.1, -0.1],
       [-0.9,  0. ,  0.2,  0. ,  0. ,  0. ],
       [-1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. , -1. ,  0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. , -1. ,  0. ,  0. ,  1. ]])

In [ ]:
A_3 = np.array([[0.4,0.2,0],[0,0.1,0.3],[0,0.1,0.3]])
phi = np.array([[2],[1],[0]])

In [ ]:
np.eye(3)-A_3

array([[ 0.6, -0.2,  0. ],
       [ 0. ,  0.9, -0.3],
       [ 0. , -0.1,  0.7]])

In [ ]:
print("Matriz A:")
print(A)

Matriz A:
[[ 0.7  0.1  0.  -0.2  0.   0. ]
 [ 0.   0.4  0.1  0.   0.1  0.1]
 [ 0.9  0.   0.8  0.   0.   0. ]
 [ 1.   0.   0.   0.   0.   0. ]
 [ 0.   1.   0.   0.   0.   0. ]
 [ 0.   0.   1.   0.   0.   0. ]]


In [ ]:
print("Vector psi:")
print(V)

Vector psi:
[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]


Luego haciendo:
\begin{align*}
det(I_6-zA) &= \frac{z^6}{z^6}det(I_6-zA)\\
&= z^6det(\frac{1}{z}I_6-A)\\
&= z^6 det(A-\lambda I_6)(-1)^6 \quad \lambda = 1/z\\
&= z^6 polcar(A)\\
\end{align*}

In [ ]:
c = np.round((np.poly(A_3)),decimals = 3);
coeff = np.zeros(6);
np.roots([0.16,-0.8,1])


array([2.5, 2.5])

In [ ]:
for i in range(3):
  coeff[i] = c[2-i]
np.roots(coeff)

array([2.5, 2.5])

b)

In [ ]:
A

array([[ 0.7,  0.1,  0. , -0.2,  0. ,  0. ],
       [ 0. ,  0.4,  0.1,  0. ,  0.1,  0.1],
       [ 0.9,  0. ,  0.8,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ]])

In [ ]:
I-A


array([[ 0.3, -0.1,  0. ,  0.2,  0. ,  0. ],
       [ 0. ,  0.6, -0.1,  0. , -0.1, -0.1],
       [-0.9,  0. ,  0.2,  0. ,  0. ,  0. ],
       [-1. ,  0. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. , -1. ,  0. ,  0. ,  1. ,  0. ],
       [ 0. ,  0. , -1. ,  0. ,  0. ,  1. ]])

In [ ]:
np.linalg.inv(I-A)

array([[ 3.125  ,  0.625  ,  0.625  , -0.625  ,  0.0625 ,  0.0625 ],
       [ 5.625  ,  3.125  ,  3.125  , -1.125  ,  0.3125 ,  0.3125 ],
       [14.0625 ,  2.8125 ,  7.8125 , -2.8125 ,  0.28125,  0.28125],
       [ 3.125  ,  0.625  ,  0.625  ,  0.375  ,  0.0625 ,  0.0625 ],
       [ 5.625  ,  3.125  ,  3.125  , -1.125  ,  1.3125 ,  0.3125 ],
       [14.0625 ,  2.8125 ,  7.8125 , -2.8125 ,  0.28125,  1.28125]])

In [ ]:
Mu = np.dot(np.linalg.inv(I-A),V)
J = np.block([np.eye(3),np.zeros((3,3))])
media = np.dot(J,Mu)
print("Vector de medias  \n {0}".format(media))

Vector de medias  
 [[ 6.875 ]
 [14.375 ]
 [30.9375]]


In [ ]:
Mu

array([[ 6.875 ],
       [14.375 ],
       [30.9375],
       [ 6.875 ],
       [14.375 ],
       [30.9375]])

c) Hecha en el informe

d) 

In [ ]:
A.shape

(6, 6)

In [ ]:
#Calcula la potencia de una matriz
def powerarray(array,n):
  (a,b) = array.shape
  if a != b:
    print("Array is not square")
    return None
  else:
    if n==0:
      return np.eye(a)
    elif n==1:
      return array
    else:
      var = np.dot(array,powerarray(array,n-1))
      return var

In [ ]:
J

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [ ]:
np.transpose(J)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
phi_1 = np.dot(np.dot(J,powerarray(A,1)),np.transpose(J));
phi_2 = np.dot(np.dot(J,powerarray(A,2)),np.transpose(J));
phi_3 = np.dot(np.dot(J,powerarray(A,3)),np.transpose(J));
phi_4 = np.dot(np.dot(J,powerarray(A,4)),np.transpose(J));
phi_5 = np.dot(np.dot(J,powerarray(A,5)),np.transpose(J));
print("Matriz phi_1 =\n {0}\n".format(phi_1))
print("Matriz phi_2 =\n {0}\n".format(phi_2))
print("Matriz phi_3 =\n {0}\n".format(phi_3))
print("Matriz phi_4 =\n {0}\n".format(phi_4))
print("Matriz phi_5 =\n {0}\n".format(phi_5))

Matriz phi_1 =
 [[0.7 0.1 0. ]
 [0.  0.4 0.1]
 [0.9 0.  0.8]]

Matriz phi_2 =
 [[0.29 0.11 0.01]
 [0.09 0.26 0.22]
 [1.35 0.09 0.64]]

Matriz phi_3 =
 [[0.072 0.083 0.029]
 [0.261 0.153 0.242]
 [1.341 0.171 0.521]]

Matriz phi_4 =
 [[0.0185 0.0514 0.0425]
 [0.3825 0.1133 0.2349]
 [1.1376 0.2115 0.4429]]

Matriz phi_5 =
 [[0.0368  0.03071 0.04744]
 [0.42696 0.09887 0.21455]
 [0.92673 0.21546 0.39257]]



In [ ]:
np.dot(np.dot(J,A),np.transpose(J))

array([[0.7, 0.1, 0. ],
       [0. , 0.4, 0.1],
       [0.9, 0. , 0.8]])