In [52]:
import numpy as np
import sympy as sp
import scipy.stats

In [53]:
I = np.eye(6)
A1 = np.array([[0.7,0.1,0],[0,0.4,0.1],[0.9,0,0.8]]);
A2 = np.array([[-0.2,0,0],[0,0.1,0.1],[0,0,0]])
A = np.block([[A1,A2],[np.eye(3),np.zeros((3,3))]])
v = np.array([[2],[1],[0]])
V = np.block([[v],[np.zeros((3,1))]])
B = np.array([[10,2,0,2,0.2,0.2],[0,2,0,0,0.2,0.2],
[45,9,5,9,0.9,0.9],
[10,2,0,3,0.2,0.2],
[0,2,0,0,1.2,0.2],
[45,9,5,9,0.9,1.9]])
Sigmau = np.array([[0.26,0.03,0],[0.03,0.09,0],[0,0,0.81]])
P = np.array([[0.5,0.1,0],[0,0.3,0],[0,0,0.9]])

Pregunta 1


In [54]:
SigmaU = np.block([[Sigmau,np.zeros((3,3))],[np.zeros((3,3)),np.zeros((3,3))]])
#SigmaU = np.array([[0.26,0.03,0],[0.03,0.09,0],[0,0,0.81]])
SigmaU

array([[0.26, 0.03, 0.  , 0.  , 0.  , 0.  ],
       [0.03, 0.09, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.81, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [55]:
np.dot(P,np.transpose(P))

array([[0.26, 0.03, 0.  ],
       [0.03, 0.09, 0.  ],
       [0.  , 0.  , 0.81]])

In [56]:
A3 = np.array([[0.4,0.2,0],[0,0.1,0.3],[0,0.1,0.3]])
B= np.eye(9)-np.kron(A3,A3)
B

array([[ 0.84, -0.08,  0.  , -0.08, -0.04,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.96, -0.12,  0.  , -0.02, -0.06,  0.  ,  0.  ,  0.  ],
       [ 0.  , -0.04,  0.88,  0.  , -0.02, -0.06,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.96, -0.02,  0.  , -0.12, -0.06,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.99, -0.03,  0.  , -0.03, -0.09],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.01,  0.97,  0.  , -0.03, -0.09],
       [ 0.  ,  0.  ,  0.  , -0.04, -0.02,  0.  ,  0.88, -0.06,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.01, -0.03,  0.  ,  0.97, -0.09],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.01, -0.03,  0.  , -0.03,  0.91]])

In [57]:
B = np.eye(36)-np.kron(A,A)   # I_{kp}`2 - kron(A,A)
B.shape

(36, 36)

In [58]:
#np.dot(np.linalg.inv(B),SigmaU.reshape(36,1)).reshape(1,36)

In [59]:
Gamma = np.dot(np.linalg.inv(B),SigmaU.reshape(36,1)).reshape(6,6)
Gamma0 = np.dot(np.linalg.inv(B),SigmaU.reshape(36,1)).reshape(6,6)[:3,:3]
Gamma1 = np.dot(np.linalg.inv(B),SigmaU.reshape(36,1)).reshape(6,6)[:3,3:6]
Gamma2 = np.dot(A1,Gamma1)+np.dot(A2,Gamma0)
Gamma3 = np.dot(A1,Gamma2)+np.dot(A2,Gamma1)

In [60]:
print("Gamma = \n{0}".format(Gamma))
print("Gamma0 = \n{0}".format(Gamma0))
print("Gamma1 = \n{0}".format(Gamma1))
print("Gamma2 = \n{0}".format(Gamma2))
print("Gamma3 = \n{0}".format(Gamma3))

Gamma = 
[[0.44718166 0.19139482 0.55695933 0.27680553 0.18059136 0.38479294]
 [0.19139482 0.84373443 1.64527596 0.18879229 0.76271303 1.84420362]
 [0.55695933 1.64527596 5.48399604 0.84803095 1.48847611 4.88846023]
 [0.27680553 0.18879229 0.84803095 0.44718166 0.19139482 0.55695933]
 [0.18059136 0.76271303 1.48847611 0.19139482 0.84373443 1.64527596]
 [0.38479294 1.84420362 4.88846023 0.55695933 1.64527596 5.48399604]]
Gamma0 = 
[[0.44718166 0.19139482 0.55695933]
 [0.19139482 0.84373443 1.64527596]
 [0.55695933 1.64527596 5.48399604]]
Gamma1 = 
[[0.27680553 0.18059136 0.38479294]
 [0.18879229 0.76271303 1.84420362]
 [0.84803095 1.48847611 4.88846023]]
Gamma2 = 
[[0.12320677 0.16440629 0.34238355]
 [0.23515543 0.70283386 1.93945467]
 [0.92754974 1.35331311 4.25708183]]
Gamma3 = 
[[0.05439918 0.14924952 0.35665537]
 [0.29049947 0.64158377 1.87475644]
 [0.85292589 1.23061615 3.71381066]]


In [61]:
D = np.diagflat([np.sqrt(Gamma0[0,0]),np.sqrt(Gamma0[1,1]),np.sqrt(Gamma0[2,2])])
Dinv = np.linalg.inv(D)
R0 = np.dot(np.dot(Dinv,Gamma0),Dinv)
R1 = np.dot(np.dot(Dinv,Gamma1),Dinv)
R2 = np.dot(np.dot(Dinv,Gamma2),Dinv)
R3 = np.dot(np.dot(Dinv,Gamma3),Dinv)

In [62]:
print("D = \n{0}".format(D))
print("R0 = \n{0}".format(R0))
print("R1 = \n{0}".format(R1))
print("R2 = \n{0}".format(R2))
print("R3 = \n{0}".format(R3))

D = 
[[0.66871642 0.         0.        ]
 [0.         0.91855018 0.        ]
 [0.         0.         2.34179334]]
R0 = 
[[1.         0.31159129 0.35565828]
 [0.31159129 1.         0.76486942]
 [0.35565828 0.76486942 1.        ]]
R1 = 
[[0.6190002  0.29400322 0.24571775]
 [0.30735436 0.90397287 0.85734855]
 [0.54152829 0.69197502 0.89140477]]
R2 = 
[[0.27551839 0.26765389 0.21863633]
 [0.38283367 0.83300365 0.90162964]
 [0.59230671 0.62913933 0.77627369]]
R3 = 
[[0.12164894 0.24297862 0.22774991]
 [0.47293393 0.76040961 0.8715522 ]
 [0.54465405 0.57209896 0.67720885]]


In [63]:
import pandas as pd
import altair as alt

In [64]:
H = np.transpose(np.array([[0,1,2,3]]))
df = (pd.DataFrame(
    np.block([H,np.block([[R0.reshape(1,9)],[R1.reshape(1,9)],[R2.reshape(1,9)],[R3.reshape(1,9)]])]),
    columns = ["h","R11","R12","R13","R21","R22","R23","R31","R32","R33"]))

df

h       R11       R12       R13       R21       R22       R23       R31  \
0  0.0  1.000000  0.311591  0.355658  0.311591  1.000000  0.764869  0.355658   
1  1.0  0.619000  0.294003  0.245718  0.307354  0.903973  0.857349  0.541528   
2  2.0  0.275518  0.267654  0.218636  0.382834  0.833004  0.901630  0.592307   
3  3.0  0.121649  0.242979  0.227750  0.472934  0.760410  0.871552  0.544654   

        R32       R33  
0  0.764869  1.000000  
1  0.691975  0.891405  
2  0.629139  0.776274  
3  0.572099  0.677209

In [65]:
###-----------------------------------GRAFICOS DE R(h)------------------------------------------- ###

In [66]:
baseh = alt.Chart(df).mark_line(point=True).encode(
    alt.X("h:O")
)
R11plot = baseh.encode(
    alt.Y("R11:Q")    
).properties(title="Componente R11(h) ")

R12plot = baseh.encode(
    alt.Y("R12:Q")    
).properties(title="Componente R12(h) ")

R13plot = baseh.encode(
    alt.Y("R13:Q")    
).properties(title="Componente R13(h) ")

R21plot = baseh.encode(
    alt.Y("R21:Q")    
).properties(title="Componente R21(h) ")

R22plot = baseh.encode(
    alt.Y("R22:Q")    
).properties(title="Componente R22(h) ")

R23plot = baseh.encode(
    alt.Y("R23:Q")    
).properties(title="Componente R23(h) ")

R31plot = baseh.encode(
    alt.Y("R31:Q")    
).properties(title="Componente R31(h) ")

R32plot = baseh.encode(
    alt.Y("R32:Q")    
).properties(title="Componente R32(h) ")

R33plot = baseh.encode(
    alt.Y("R33:Q")    
).properties(title="Componente R33(h) ")

R11plot|R12plot|R13plot|R21plot|R22plot|R23plot|R31plot|R32plot|R33plot

alt.HConcatChart(...)

Pregunta 2

a)

In [67]:
y1999 = np.transpose(np.array([[1,1.5,3]]))
y2000 = np.transpose(np.array([[0.7,1,1.5]]))


In [68]:
Mu = np.dot(np.linalg.inv(I-A),V)
J = np.block([np.eye(3),np.zeros((3,3))])
media = np.dot(J,Mu)

In [69]:
z1999 = y1999-media
z2000 = y2000-media
print(z1999)
print(z2000)

[[ -5.875 ]
 [-12.875 ]
 [-27.9375]]
[[ -6.175 ]
 [-13.375 ]
 [-29.4375]]


In [70]:
z2001 = np.dot(A1,z2000)+np.dot(A2,z1999)
z2002 = np.dot(A1,z2001)+np.dot(A2,z2000)
z2003 = np.dot(A1,z2002)+np.dot(A2,z2001)
y2001 = z2001 + media
y2002 = z2002 + media
y2003 = z2003 + media

In [71]:
print("y2001 = \n {0}\n y2002 = \n {1}\n y2003 = \n {2}".format(y2001,y2002,y2003))

y2001 = 
 [[2.39]
 [2.  ]
 [1.83]]
 y2002 = 
 [[3.733]
 [2.233]
 [3.615]]
 y2003 = 
 [[4.3584]
 [2.6377]
 [6.2517]]


b)

In [72]:
#Calcula la potencia de una matriz
def powerarray(array,n):
  (a,b) = array.shape
  if a != b:
    print("Array is not square")
    return None
  else:
    if n==0:
      return np.eye(a)
    elif n==1:
      return array
    else:
      var = np.dot(array,powerarray(array,n-1))
      return var

In [73]:
phi = list();
N = 5
for n in range(N+1):
  (phi.append(
      np.dot(np.dot(J,powerarray(A,n)),np.transpose(J))
  )
  )

In [74]:
sum([np.array([[1,2],[3,4]]),np.array([[1,5],[3,4]])])

array([[2, 7],
       [6, 8]])

In [75]:
Sigmay = list();
for h in range(1,4):
  suma = list()
  for i in range(h):
    (suma.append(
        np.dot(np.dot(phi[i],Sigmau),np.transpose(phi[i])
    ))
    )
  Sigmay.append(sum(suma))
  print("Sigmay({0}) = \n {1} \n".format(h,Sigmay[h-1]))

Sigmay(1) = 
 [[0.26 0.03 0.  ]
 [0.03 0.09 0.  ]
 [0.   0.   0.81]] 

Sigmay(2) = 
 [[0.3925 0.042  0.1665]
 [0.042  0.1125 0.0756]
 [0.1665 0.0756 1.539 ]] 

Sigmay(3) = 
 [[0.41745  0.055701 0.279603]
 [0.055701 0.161298 0.234117]
 [0.279603 0.234117 2.352645]] 



c)


In [76]:
ylist = [y2001,y2002,y2003]
confianza = [0.90,0.95]
Intervalos = dict()
for alpha in confianza:
  zaph = scipy.stats.norm.ppf(1-alpha/2)
  for h in range(3):
    for k in range(3):
      key = "y200{0}_{1} conf = {2}%".format(h+1,k+1,100*alpha,)
      LI = round(ylist[h][k,0] - zaph*np.sqrt(Sigmay[h][k,k]),4)
      LS = round(ylist[h][k,0] + zaph*np.sqrt(Sigmay[h][k,k]),4)
      Intervalos[key] = (LI,LS)

Intervalos

{'y2001_1 conf = 90.0%': (2.3259, 2.4541),
 'y2001_2 conf = 90.0%': (1.9623, 2.0377),
 'y2001_3 conf = 90.0%': (1.7169, 1.9431),
 'y2002_1 conf = 90.0%': (3.6543, 3.8117),
 'y2002_2 conf = 90.0%': (2.1909, 2.2751),
 'y2002_3 conf = 90.0%': (3.4591, 3.7709),
 'y2003_1 conf = 90.0%': (4.2772, 4.4396),
 'y2003_2 conf = 90.0%': (2.5872, 2.6882),
 'y2003_3 conf = 90.0%': (6.059, 6.4444),
 'y2001_1 conf = 95.0%': (2.358, 2.422),
 'y2001_2 conf = 95.0%': (1.9812, 2.0188),
 'y2001_3 conf = 95.0%': (1.7736, 1.8864),
 'y2002_1 conf = 95.0%': (3.6937, 3.7723),
 'y2002_2 conf = 95.0%': (2.212, 2.254),
 'y2002_3 conf = 95.0%': (3.5372, 3.6928),
 'y2003_1 conf = 95.0%': (4.3179, 4.3989),
 'y2003_2 conf = 95.0%': (2.6125, 2.6629),
 'y2003_3 conf = 95.0%': (6.1555, 6.3479)}

d)

In [77]:
ylist = [y2001,y2002,y2003]
confianza = [0.99]
Intervalos = dict()
for alpha in confianza:
  zaph = scipy.stats.norm.ppf(1-alpha/2)
  for h in range(3):
    key = "GNP_200{0} conf = {1}%".format(h+1,100*alpha,)
    LI = round(ylist[h][0,0] - zaph*np.sqrt(Sigmay[h][0,0]),4)
    LS = round(ylist[h][0,0] + zaph*np.sqrt(Sigmay[h][0,0]),4)
    Intervalos[key] = (LI,LS)

Intervalos


{'GNP_2001 conf = 99.0%': (2.3836, 2.3964),
 'GNP_2002 conf = 99.0%': (3.7251, 3.7409),
 'GNP_2003 conf = 99.0%': (4.3503, 4.3665)}